version: '2'

services:
    app: 
       build: app
       ports:
        - "9000"
       volumes:
        - "./app/server:/code"
    proxy:
       build: proxy
       ports:
         - "80:80"
       volumes: 
         - "./proxy:/etc/nginx/conf.d/"  


